### ISSUE TITLE
[SOLVED]It doesn't work in Unity 2018.3.11f

### ISSUE THREAD

**Issue by I-forgot-the-semicolon** [flamacore/UnityHDRPSimpleWater#1]
The shader shows nothing.
![1](https://user-images.githubusercontent.com/42678250/55252530-71694b80-5253-11e9-88db-af4a05f11ac2.jpg)
![2](https://user-images.githubusercontent.com/42678250/55252531-71694b80-5253-11e9-8d35-0f5dda8d57e8.jpg)

**Comment by flamacore** [comment]
Are you using HDRP? (Seems like so but just to be safe :) )

**Comment by flamacore** [comment]
Also, do you have ShaderGraph installed from the Package Manager?

**Comment by I-forgot-the-semicolon** [comment]
Yeah x2, hehehe, HDRP and ShaderGraph latest version ^^

**Comment by flamacore** [comment]
Allright, could you please also increase heights of other waves as well? They might be causing some flunky business behind. And can you please try on a cube rather than a plane instead? Backface culling might be at work here although it should render double-sided

**Comment by I-forgot-the-semicolon** [comment]
Omw mate, anyway I tried in a cube as well ^^

**Comment by I-forgot-the-semicolon** [comment]
![3](https://user-images.githubusercontent.com/42678250/55253436-a37bad00-5255-11e9-858b-66b3114d84ca.png)

**Comment by flamacore** [comment]
Hmm allright. Do not have the exact workspace right here right now but I can suggest removing HDRP and Shadergraph and then installing the version 4.9.0 as this shader was made on that.

**Comment by I-forgot-the-semicolon** [comment]
Think I found the problem, when the shader graph is imported, You have to drag n drop the sub-shader graph, seems a bug from unity.
![4](https://user-images.githubusercontent.com/42678250/55253664-416f7780-5256-11e9-992a-eecca001a890.png)
![5](https://user-images.githubusercontent.com/42678250/55253669-446a6800-5256-11e9-9a67-5a62e4101b4a.png)

**Comment by flamacore** [comment]
Oh ok that's definitely strange! :) I assume you tried re-importing?

**Comment by I-forgot-the-semicolon** [comment]
I just looked for what was missing hehe, i'll try to connect it and see if it works!

**Comment by flamacore** [comment]
once we have a solution, I'll pin this for sure since it's probably related to Unity Editor itself.

**Comment by I-forgot-the-semicolon** [comment]
It looks slightly different from yours...  xD
![6](https://user-images.githubusercontent.com/42678250/55254266-bb543080-5257-11e9-9418-c684471da092.png)
Can u attach ur waves values to debug it?

**Comment by flamacore** [comment]
Can you try reducing tiling to 25x25 or even less? Seems like it's tiling issue :) Also, one polygon per-face so there will be no waving :)

**Comment by I-forgot-the-semicolon** [comment]
Same result with < 25x25, the corners go up and down, nothing changes ^^

**Comment by flamacore** [comment]
Allright so here's my idea. Since it started to render something, you can even go lower than 1 for tiling. To 0.1 or even 0.01 just to try it out. Does it show the normal maps when you reduce the tiling so low? For objects with low polygons, the waves will not work as they move vertexes and this cube has only 8 vertexes thus only the corners move :)

I guess we can achieve something by trying to see the tiling first. At least we have to be able to see the normal maps moving with those settings.

**Comment by I-forgot-the-semicolon** [comment]
It works fine, I just have to tweak it a bit ^^
![10](https://user-images.githubusercontent.com/42678250/55255047-d9229500-5259-11e9-9929-e1c2bf03dd25.png)
You are using Gerstner waves, true?
The cube has only 8 vertices and the waves works with vertices displacement, are u using a high poly mesh in your video?
Thanks so much for ur time!

**Comment by flamacore** [comment]
Might come to your surprise but I have no idea what a Gerstner wave is :) So probably no, just came up with simple sine wave and tweaked it with values like -1 and absolution, thus the result. 

Long answer; Well I am using a huge poly mesh with a gigantic size reaching over the entire terrain so to answer your question; Generally around 5k polygons are visible to the camera when looking at the mesh in any angle from anywhere. 

Short answer; yes, a bit high poly mesh :) At least not 8 vertices :D

I'm counting this one as closed. Thanks for pointing out.
