### ISSUE TITLE
It doesn't work in Unity 2019.2.0b7

### ISSUE THREAD

**Issue by KostaDokosic** [flamacore/UnityHDRPSimpleWater#2]
I have installed latest version HDRP: 6.7.1 and water is purple:
[url=https://ibb.co/Tg5s2WX][img]https://i.ibb.co/sVrZRWS/Capture.png[/img][/url]

**Comment by AmitloafTotes** [comment]
Shader is broken - you don't see any shader properties in the inspector. Open in Shader Graph. You should see a red exclamation mark near the SubShader. Reconnect the subshader and reimport the shader. It should take care of it.

**Comment by KostaDokosic** [comment]
Thanks that fix purple color but now water plane is invisible.There is animations on object but no color.
![Capture](https://user-images.githubusercontent.com/18070769/61060796-677ee900-a3fb-11e9-8f83-84672fae9422.PNG)

**Comment by DenisLabrecque** [comment]
> Shader is broken - you don't see any shader properties in the inspector. Open in Shader Graph. You should see a red exclamation mark near the SubShader. Reconnect the subshader and reimport the shader. It should take care of it.

How do you reconnect to the subgraph? This is ridiculously frustrating.

**Comment by enqui** [comment]
Hi, this looks like a very nice shader did anyone manage to make it work in newer Unity versions?

**Comment by ColinAllmanGame** [comment]
Furthering this. reconnected subgraph and reimported, still have similar problems

**Comment by Antony-Melendez** [comment]
Just use the material from the sample scene it has, that's how I fixed it.

**Comment by enqui** [comment]
> Just use the material from the sample scene it has, that's how I fixed it.

Hi, which version of Unity did you fix it for? 
Does it also work with 19.3? 

Thank you.

**Comment by flamacore** [comment]
Wow ok. I did not realise how much exposure this got. Replying with the same text to the other issue above; Added a unitypackage with a working scene for 2019.3.1f1. Should be working fine now. And also included a tiny bit readme in it :)
