### ISSUE TITLE
2019.1 (5.16.1) - Completely Transparent

### ISSUE THREAD

**Issue by AmitloafTotes** [flamacore/UnityHDRPSimpleWater#3]
So, I reconnected the SubShader as in the other issues, and now I see all the properties but the shader itself is completely transparent. Also, it seems like the waves are really tall.
Can you help?
Also can you send an example (maybe a scene?) with a working example, with proper normal textures and correct values?

![image](https://user-images.githubusercontent.com/44541987/61056906-e3c5fc00-a3fc-11e9-83c6-c125b0adcb9b.png)

**Comment by flamacore** [comment]
Added a unitypackage with a working scene for 2019.3.1f1. Should be working fine now. And also included a tiny bit readme in it :)
